services:
  - type: web
    name: test
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:create_app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        value: your_secret_key
